import { InferInsertModel } from "drizzle-orm";
import { db } from "@/lib/drizzle";
import { PamCabeceraSemanal } from "@/db/schema/PAM_CABECERA_SEMANAL";
import { chunkArray } from "@/shared/utils/chunks";

export type NuevaCabeceraSemanal = InferInsertModel<typeof PamCabeceraSemanal>;

export async function seedPamCabeceraSemanal() {
  // Asumiendo que tenemos 12 semanas (ids 1-12)
  const cabeceras: NuevaCabeceraSemanal[] = [
    {
      id: 2,
      semanaId: 6,
      analistaId: 5,
      saldoAnterior: 2,
      nuevoIngreso: 6,
      circulacion: 1,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 2,
      historicoCirculacion: 1,
    },
    {
      id: 3,
      semanaId: 5,
      analistaId: 5,
      saldoAnterior: 0,
      nuevoIngreso: 8,
      circulacion: 0,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 2,
      historicoCirculacion: 0,
    },
    {
      id: 4,
      semanaId: 2,
      analistaId: 1,
      saldoAnterior: 0,
      nuevoIngreso: 24,
      circulacion: 0,
      resuelto: 11,
      conLugar: 11,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 6,
      pendiente: 7,
      historicoCirculacion: 0,
    },
    {
      id: 5,
      semanaId: 2,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 17,
      circulacion: 0,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 8,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 0,
    },
    {
      id: 6,
      semanaId: 6,
      analistaId: 8,
      saldoAnterior: 7,
      nuevoIngreso: 15,
      circulacion: 4,
      resuelto: 18,
      conLugar: 18,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 7,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 3,
    },
    {
      id: 7,
      semanaId: 2,
      analistaId: 8,
      saldoAnterior: 0,
      nuevoIngreso: 14,
      circulacion: 0,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 0,
      historicoCirculacion: 0,
    },
    {
      id: 8,
      semanaId: 6,
      analistaId: 2,
      saldoAnterior: 5,
      nuevoIngreso: 7,
      circulacion: 2,
      resuelto: 11,
      conLugar: 9,
      sinLugar: 0,
      parcial: 2,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 9,
    },
    {
      id: 10,
      semanaId: 3,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 2,
      circulacion: 0,
      resuelto: 1,
      conLugar: 1,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 9,
    },
    {
      id: 11,
      semanaId: 3,
      analistaId: 8,
      saldoAnterior: 0,
      nuevoIngreso: 6,
      circulacion: 1,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 6,
    },
    {
      id: 12,
      semanaId: 2,
      analistaId: 2,
      saldoAnterior: 0,
      nuevoIngreso: 15,
      circulacion: 0,
      resuelto: 7,
      conLugar: 6,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 1,
      dictamenCirculacion: 1,
      requerido: 6,
      pendiente: 0,
      historicoCirculacion: 0,
    },
    {
      id: 14,
      semanaId: 3,
      analistaId: 2,
      saldoAnterior: 0,
      nuevoIngreso: 7,
      circulacion: 1,
      resuelto: 6,
      conLugar: 5,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 7,
    },
    {
      id: 15,
      semanaId: 4,
      analistaId: 8,
      saldoAnterior: 1,
      nuevoIngreso: 11,
      circulacion: 2,
      resuelto: 11,
      conLugar: 11,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 4,
    },
    {
      id: 16,
      semanaId: 5,
      analistaId: 8,
      saldoAnterior: 2,
      nuevoIngreso: 9,
      circulacion: 0,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 7,
      historicoCirculacion: 5,
    },
    {
      id: 17,
      semanaId: 4,
      analistaId: 2,
      saldoAnterior: 0,
      nuevoIngreso: 8,
      circulacion: 4,
      resuelto: 6,
      conLugar: 4,
      sinLugar: 0,
      parcial: 1,
      caducado: 1,
      dictamen: 3,
      dictamenCustodia: 3,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 1,
      historicoCirculacion: 5,
    },
    {
      id: 18,
      semanaId: 3,
      analistaId: 1,
      saldoAnterior: 7,
      nuevoIngreso: 9,
      circulacion: 3,
      resuelto: 11,
      conLugar: 11,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 5,
      historicoCirculacion: 3,
    },
    {
      id: 19,
      semanaId: 7,
      analistaId: 5,
      saldoAnterior: 3,
      nuevoIngreso: 7,
      circulacion: 1,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 3,
      historicoCirculacion: 2,
    },
    {
      id: 20,
      semanaId: 4,
      analistaId: 1,
      saldoAnterior: 5,
      nuevoIngreso: 5,
      circulacion: 5,
      resuelto: 9,
      conLugar: 8,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 1,
      dictamenCirculacion: 1,
      requerido: 2,
      pendiente: 2,
      historicoCirculacion: 1,
    },
    {
      id: 21,
      semanaId: 5,
      analistaId: 1,
      saldoAnterior: 2,
      nuevoIngreso: 8,
      circulacion: 1,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 1,
      dictamenCirculacion: 2,
      requerido: 1,
      pendiente: 7,
      historicoCirculacion: 4,
    },
    {
      id: 22,
      semanaId: 6,
      analistaId: 1,
      saldoAnterior: 7,
      nuevoIngreso: 5,
      circulacion: 2,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 4,
      historicoCirculacion: 6,
    },
    {
      id: 23,
      semanaId: 7,
      analistaId: 1,
      saldoAnterior: 4,
      nuevoIngreso: 7,
      circulacion: 2,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 6,
      historicoCirculacion: 8,
    },
    {
      id: 24,
      semanaId: 2,
      analistaId: 3,
      saldoAnterior: 0,
      nuevoIngreso: 28,
      circulacion: 0,
      resuelto: 14,
      conLugar: 10,
      sinLugar: 1,
      parcial: 2,
      caducado: 1,
      dictamen: 2,
      dictamenCustodia: 1,
      dictamenCirculacion: 1,
      requerido: 5,
      pendiente: 7,
      historicoCirculacion: 0,
    },
    {
      id: 26,
      semanaId: 7,
      analistaId: 8,
      saldoAnterior: 1,
      nuevoIngreso: 14,
      circulacion: 0,
      resuelto: 11,
      conLugar: 11,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 10,
    },
    {
      id: 27,
      semanaId: 2,
      analistaId: 7,
      saldoAnterior: 0,
      nuevoIngreso: 13,
      circulacion: 0,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 0,
    },
    {
      id: 28,
      semanaId: 2,
      analistaId: 10,
      saldoAnterior: 0,
      nuevoIngreso: 12,
      circulacion: 0,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 0,
      historicoCirculacion: 0,
    },
    {
      id: 29,
      semanaId: 3,
      analistaId: 10,
      saldoAnterior: 0,
      nuevoIngreso: 6,
      circulacion: 0,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 6,
    },
    {
      id: 31,
      semanaId: 3,
      analistaId: 7,
      saldoAnterior: 0,
      nuevoIngreso: 5,
      circulacion: 1,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 4,
    },
    {
      id: 32,
      semanaId: 4,
      analistaId: 7,
      saldoAnterior: 0,
      nuevoIngreso: 12,
      circulacion: 0,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 5,
    },
    {
      id: 33,
      semanaId: 5,
      analistaId: 2,
      saldoAnterior: 1,
      nuevoIngreso: 7,
      circulacion: 0,
      resuelto: 2,
      conLugar: 1,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 5,
      historicoCirculacion: 10,
    },
    {
      id: 34,
      semanaId: 2,
      analistaId: 9,
      saldoAnterior: 0,
      nuevoIngreso: 13,
      circulacion: 0,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 5,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 0,
      historicoCirculacion: 0,
    },
    {
      id: 35,
      semanaId: 3,
      analistaId: 9,
      saldoAnterior: 0,
      nuevoIngreso: 5,
      circulacion: 2,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 5,
    },
    {
      id: 36,
      semanaId: 5,
      analistaId: 7,
      saldoAnterior: 1,
      nuevoIngreso: 9,
      circulacion: 4,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 11,
      historicoCirculacion: 4,
    },
    {
      id: 37,
      semanaId: 4,
      analistaId: 9,
      saldoAnterior: 0,
      nuevoIngreso: 10,
      circulacion: 1,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 5,
    },
    {
      id: 38,
      semanaId: 7,
      analistaId: 2,
      saldoAnterior: 3,
      nuevoIngreso: 5,
      circulacion: 1,
      resuelto: 5,
      conLugar: 4,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 2,
      pendiente: 1,
      historicoCirculacion: 8,
    },
    {
      id: 39,
      semanaId: 5,
      analistaId: 9,
      saldoAnterior: 2,
      nuevoIngreso: 9,
      circulacion: 4,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 11,
      historicoCirculacion: 3,
    },
    {
      id: 40,
      semanaId: 6,
      analistaId: 9,
      saldoAnterior: 11,
      nuevoIngreso: 15,
      circulacion: 0,
      resuelto: 19,
      conLugar: 19,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 2,
      historicoCirculacion: 7,
    },
    {
      id: 41,
      semanaId: 6,
      analistaId: 7,
      saldoAnterior: 11,
      nuevoIngreso: 15,
      circulacion: 1,
      resuelto: 20,
      conLugar: 20,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 6,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 6,
    },
    {
      id: 42,
      semanaId: 7,
      analistaId: 9,
      saldoAnterior: 2,
      nuevoIngreso: 14,
      circulacion: 3,
      resuelto: 11,
      conLugar: 9,
      sinLugar: 2,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 6,
      historicoCirculacion: 9,
    },
    {
      id: 43,
      semanaId: 3,
      analistaId: 3,
      saldoAnterior: 7,
      nuevoIngreso: 9,
      circulacion: 4,
      resuelto: 11,
      conLugar: 9,
      sinLugar: 1,
      parcial: 0,
      caducado: 1,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 5,
      pendiente: 3,
      historicoCirculacion: 3,
    },
    {
      id: 44,
      semanaId: 4,
      analistaId: 3,
      saldoAnterior: 3,
      nuevoIngreso: 5,
      circulacion: 4,
      resuelto: 7,
      conLugar: 3,
      sinLugar: 2,
      parcial: 1,
      caducado: 1,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 3,
      historicoCirculacion: 5,
    },
    {
      id: 45,
      semanaId: 5,
      analistaId: 3,
      saldoAnterior: 3,
      nuevoIngreso: 8,
      circulacion: 0,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 5,
      historicoCirculacion: 7,
    },
    {
      id: 46,
      semanaId: 6,
      analistaId: 3,
      saldoAnterior: 5,
      nuevoIngreso: 4,
      circulacion: 2,
      resuelto: 4,
      conLugar: 3,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 6,
      historicoCirculacion: 6,
    },
    {
      id: 47,
      semanaId: 8,
      analistaId: 2,
      saldoAnterior: 1,
      nuevoIngreso: 8,
      circulacion: 1,
      resuelto: 6,
      conLugar: 5,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 2,
      historicoCirculacion: 11,
    },
    {
      id: 48,
      semanaId: 4,
      analistaId: 10,
      saldoAnterior: 1,
      nuevoIngreso: 9,
      circulacion: 0,
      resuelto: 10,
      conLugar: 10,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 6,
    },
    {
      id: 49,
      semanaId: 5,
      analistaId: 10,
      saldoAnterior: 0,
      nuevoIngreso: 10,
      circulacion: 1,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 7,
      historicoCirculacion: 5,
    },
    {
      id: 50,
      semanaId: 4,
      analistaId: 6,
      saldoAnterior: 1,
      nuevoIngreso: 11,
      circulacion: 2,
      resuelto: 12,
      conLugar: 12,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 7,
    },
    {
      id: 51,
      semanaId: 5,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 7,
      circulacion: 0,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 9,
    },
    {
      id: 52,
      semanaId: 6,
      analistaId: 10,
      saldoAnterior: 7,
      nuevoIngreso: 15,
      circulacion: 0,
      resuelto: 16,
      conLugar: 16,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 1,
      historicoCirculacion: 7,
    },
    {
      id: 53,
      semanaId: 6,
      analistaId: 6,
      saldoAnterior: 3,
      nuevoIngreso: 14,
      circulacion: 7,
      resuelto: 18,
      conLugar: 18,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 6,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 4,
    },
    {
      id: 54,
      semanaId: 7,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 17,
      circulacion: 1,
      resuelto: 13,
      conLugar: 13,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 2,
      historicoCirculacion: 9,
    },
    {
      id: 55,
      semanaId: 7,
      analistaId: 10,
      saldoAnterior: 1,
      nuevoIngreso: 14,
      circulacion: 0,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 7,
      historicoCirculacion: 12,
    },
    {
      id: 56,
      semanaId: 7,
      analistaId: 3,
      saldoAnterior: 6,
      nuevoIngreso: 4,
      circulacion: 2,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 3,
      pendiente: 6,
      historicoCirculacion: 5,
    },
    {
      id: 57,
      semanaId: 2,
      analistaId: 12,
      saldoAnterior: 0,
      nuevoIngreso: 11,
      circulacion: 0,
      resuelto: 6,
      conLugar: 5,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 2,
      historicoCirculacion: 0,
    },
    {
      id: 58,
      semanaId: 3,
      analistaId: 12,
      saldoAnterior: 2,
      nuevoIngreso: 11,
      circulacion: 0,
      resuelto: 7,
      conLugar: 6,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 2,
      historicoCirculacion: 3,
    },
    {
      id: 59,
      semanaId: 4,
      analistaId: 12,
      saldoAnterior: 2,
      nuevoIngreso: 11,
      circulacion: 1,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 5,
      historicoCirculacion: 6,
    },
    {
      id: 60,
      semanaId: 5,
      analistaId: 12,
      saldoAnterior: 5,
      nuevoIngreso: 4,
      circulacion: 4,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 8,
      historicoCirculacion: 4,
    },
    {
      id: 61,
      semanaId: 8,
      analistaId: 9,
      saldoAnterior: 6,
      nuevoIngreso: 8,
      circulacion: 1,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 5,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 2,
      historicoCirculacion: 10,
    },
    {
      id: 62,
      semanaId: 2,
      analistaId: 11,
      saldoAnterior: 0,
      nuevoIngreso: 8,
      circulacion: 0,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 0,
    },
    {
      id: 63,
      semanaId: 3,
      analistaId: 11,
      saldoAnterior: 3,
      nuevoIngreso: 10,
      circulacion: 0,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 7,
      historicoCirculacion: 0,
    },
    {
      id: 64,
      semanaId: 4,
      analistaId: 11,
      saldoAnterior: 7,
      nuevoIngreso: 15,
      circulacion: 0,
      resuelto: 9,
      conLugar: 9,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 11,
      historicoCirculacion: 2,
    },
    {
      id: 65,
      semanaId: 5,
      analistaId: 11,
      saldoAnterior: 11,
      nuevoIngreso: 5,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 15,
      historicoCirculacion: 4,
    },
    {
      id: 66,
      semanaId: 6,
      analistaId: 11,
      saldoAnterior: 15,
      nuevoIngreso: 2,
      circulacion: 0,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 13,
      historicoCirculacion: 5,
    },
    {
      id: 67,
      semanaId: 7,
      analistaId: 11,
      saldoAnterior: 13,
      nuevoIngreso: 3,
      circulacion: 1,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 10,
      historicoCirculacion: 4,
    },
    {
      id: 68,
      semanaId: 8,
      analistaId: 11,
      saldoAnterior: 10,
      nuevoIngreso: 7,
      circulacion: 1,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 11,
      historicoCirculacion: 3,
    },
    {
      id: 73,
      semanaId: 2,
      analistaId: 13,
      saldoAnterior: 0,
      nuevoIngreso: 12,
      circulacion: 0,
      resuelto: 3,
      conLugar: 2,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 4,
      historicoCirculacion: 0,
    },
    {
      id: 74,
      semanaId: 3,
      analistaId: 13,
      saldoAnterior: 4,
      nuevoIngreso: 6,
      circulacion: 2,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 5,
      historicoCirculacion: 3,
    },
    {
      id: 75,
      semanaId: 4,
      analistaId: 13,
      saldoAnterior: 5,
      nuevoIngreso: 11,
      circulacion: 2,
      resuelto: 7,
      conLugar: 6,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 9,
      historicoCirculacion: 4,
    },
    {
      id: 77,
      semanaId: 5,
      analistaId: 13,
      saldoAnterior: 9,
      nuevoIngreso: 5,
      circulacion: 0,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 9,
      historicoCirculacion: 6,
    },
    {
      id: 78,
      semanaId: 2,
      analistaId: 14,
      saldoAnterior: 0,
      nuevoIngreso: 9,
      circulacion: 0,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 4,
      historicoCirculacion: 0,
    },
    {
      id: 79,
      semanaId: 6,
      analistaId: 13,
      saldoAnterior: 9,
      nuevoIngreso: 4,
      circulacion: 0,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 11,
      historicoCirculacion: 7,
    },
    {
      id: 80,
      semanaId: 3,
      analistaId: 14,
      saldoAnterior: 4,
      nuevoIngreso: 5,
      circulacion: 2,
      resuelto: 6,
      conLugar: 5,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 4,
      historicoCirculacion: 1,
    },
    {
      id: 81,
      semanaId: 4,
      analistaId: 14,
      saldoAnterior: 4,
      nuevoIngreso: 6,
      circulacion: 0,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 3,
      historicoCirculacion: 2,
    },
    {
      id: 82,
      semanaId: 7,
      analistaId: 7,
      saldoAnterior: 1,
      nuevoIngreso: 9,
      circulacion: 1,
      resuelto: 10,
      conLugar: 9,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 11,
    },
    {
      id: 83,
      semanaId: 5,
      analistaId: 14,
      saldoAnterior: 3,
      nuevoIngreso: 7,
      circulacion: 2,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 8,
      historicoCirculacion: 3,
    },
    {
      id: 84,
      semanaId: 7,
      analistaId: 13,
      saldoAnterior: 11,
      nuevoIngreso: 7,
      circulacion: 1,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 4,
      pendiente: 7,
      historicoCirculacion: 6,
    },
    {
      id: 85,
      semanaId: 6,
      analistaId: 14,
      saldoAnterior: 8,
      nuevoIngreso: 4,
      circulacion: 1,
      resuelto: 3,
      conLugar: 3,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 7,
      historicoCirculacion: 4,
    },
    {
      id: 86,
      semanaId: 7,
      analistaId: 14,
      saldoAnterior: 7,
      nuevoIngreso: 2,
      circulacion: 4,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 7,
      historicoCirculacion: 3,
    },
    {
      id: 87,
      semanaId: 6,
      analistaId: 12,
      saldoAnterior: 8,
      nuevoIngreso: 3,
      circulacion: 1,
      resuelto: 5,
      conLugar: 4,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 6,
      historicoCirculacion: 6,
    },
    {
      id: 88,
      semanaId: 7,
      analistaId: 12,
      saldoAnterior: 6,
      nuevoIngreso: 5,
      circulacion: 3,
      resuelto: 3,
      conLugar: 2,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 4,
      pendiente: 6,
      historicoCirculacion: 4,
    },
    {
      id: 89,
      semanaId: 2,
      analistaId: 15,
      saldoAnterior: 0,
      nuevoIngreso: 4,
      circulacion: 0,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 0,
    },
    {
      id: 90,
      semanaId: 3,
      analistaId: 15,
      saldoAnterior: 1,
      nuevoIngreso: 3,
      circulacion: 0,
      resuelto: 1,
      conLugar: 1,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 1,
    },
    {
      id: 91,
      semanaId: 4,
      analistaId: 15,
      saldoAnterior: 3,
      nuevoIngreso: 4,
      circulacion: 0,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 2,
      historicoCirculacion: 1,
    },
    {
      id: 92,
      semanaId: 5,
      analistaId: 15,
      saldoAnterior: 2,
      nuevoIngreso: 2,
      circulacion: 0,
      resuelto: 3,
      conLugar: 3,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 4,
    },
    {
      id: 93,
      semanaId: 6,
      analistaId: 15,
      saldoAnterior: 1,
      nuevoIngreso: 5,
      circulacion: 0,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 2,
      historicoCirculacion: 4,
    },
    {
      id: 94,
      semanaId: 2,
      analistaId: 4,
      saldoAnterior: 0,
      nuevoIngreso: 29,
      circulacion: 0,
      resuelto: 9,
      conLugar: 7,
      sinLugar: 0,
      parcial: 2,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 2,
      pendiente: 17,
      historicoCirculacion: 0,
    },
    {
      id: 95,
      semanaId: 3,
      analistaId: 4,
      saldoAnterior: 17,
      nuevoIngreso: 8,
      circulacion: 0,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 17,
      historicoCirculacion: 3,
    },
    {
      id: 96,
      semanaId: 8,
      analistaId: 7,
      saldoAnterior: 0,
      nuevoIngreso: 10,
      circulacion: 0,
      resuelto: 7,
      conLugar: 6,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 11,
    },
    {
      id: 97,
      semanaId: 4,
      analistaId: 4,
      saldoAnterior: 17,
      nuevoIngreso: 4,
      circulacion: 1,
      resuelto: 7,
      conLugar: 2,
      sinLugar: 4,
      parcial: 1,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 3,
      pendiente: 11,
      historicoCirculacion: 2,
    },
    {
      id: 98,
      semanaId: 5,
      analistaId: 4,
      saldoAnterior: 11,
      nuevoIngreso: 7,
      circulacion: 0,
      resuelto: 6,
      conLugar: 5,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 10,
      historicoCirculacion: 6,
    },
    {
      id: 99,
      semanaId: 6,
      analistaId: 4,
      saldoAnterior: 10,
      nuevoIngreso: 3,
      circulacion: 0,
      resuelto: 3,
      conLugar: 3,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 9,
      historicoCirculacion: 8,
    },
    {
      id: 100,
      semanaId: 7,
      analistaId: 4,
      saldoAnterior: 9,
      nuevoIngreso: 9,
      circulacion: 3,
      resuelto: 6,
      conLugar: 4,
      sinLugar: 0,
      parcial: 2,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 1,
      dictamenCirculacion: 2,
      requerido: 1,
      pendiente: 11,
      historicoCirculacion: 6,
    },
    {
      id: 101,
      semanaId: 8,
      analistaId: 5,
      saldoAnterior: 3,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 4,
    },
    {
      id: 102,
      semanaId: 8,
      analistaId: 1,
      saldoAnterior: 6,
      nuevoIngreso: 5,
      circulacion: 2,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 3,
      pendiente: 4,
      historicoCirculacion: 8,
    },
    {
      id: 103,
      semanaId: 8,
      analistaId: 10,
      saldoAnterior: 7,
      nuevoIngreso: 10,
      circulacion: 1,
      resuelto: 9,
      conLugar: 8,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 8,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 12,
    },
    {
      id: 104,
      semanaId: 8,
      analistaId: 6,
      saldoAnterior: 2,
      nuevoIngreso: 9,
      circulacion: 2,
      resuelto: 9,
      conLugar: 9,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 10,
    },
    {
      id: 105,
      semanaId: 8,
      analistaId: 8,
      saldoAnterior: 2,
      nuevoIngreso: 8,
      circulacion: 0,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 12,
    },
    {
      id: 106,
      semanaId: 8,
      analistaId: 3,
      saldoAnterior: 6,
      nuevoIngreso: 7,
      circulacion: 4,
      resuelto: 9,
      conLugar: 8,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 1,
      dictamenCirculacion: 1,
      requerido: 1,
      pendiente: 5,
      historicoCirculacion: 5,
    },
    {
      id: 107,
      semanaId: 8,
      analistaId: 14,
      saldoAnterior: 7,
      nuevoIngreso: 6,
      circulacion: 0,
      resuelto: 3,
      conLugar: 3,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 4,
      pendiente: 6,
      historicoCirculacion: 3,
    },
    {
      id: 108,
      semanaId: 7,
      analistaId: 15,
      saldoAnterior: 2,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 6,
    },
    {
      id: 109,
      semanaId: 8,
      analistaId: 12,
      saldoAnterior: 6,
      nuevoIngreso: 7,
      circulacion: 2,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 8,
      historicoCirculacion: 7,
    },
    {
      id: 110,
      semanaId: 8,
      analistaId: 15,
      saldoAnterior: 2,
      nuevoIngreso: 1,
      circulacion: 0,
      resuelto: 1,
      conLugar: 1,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 6,
    },
    {
      id: 111,
      semanaId: 8,
      analistaId: 13,
      saldoAnterior: 7,
      nuevoIngreso: 12,
      circulacion: 3,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 12,
      historicoCirculacion: 7,
    },
    {
      id: 112,
      semanaId: 9,
      analistaId: 9,
      saldoAnterior: 2,
      nuevoIngreso: 18,
      circulacion: 5,
      resuelto: 19,
      conLugar: 19,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 4,
      historicoCirculacion: 11,
    },
    {
      id: 113,
      semanaId: 8,
      analistaId: 17,
      saldoAnterior: 0,
      nuevoIngreso: 8,
      circulacion: 0,
      resuelto: 3,
      conLugar: 2,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 5,
      historicoCirculacion: 0,
    },
    {
      id: 114,
      semanaId: 9,
      analistaId: 1,
      saldoAnterior: 4,
      nuevoIngreso: 2,
      circulacion: 3,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 4,
      historicoCirculacion: 9,
    },
    {
      id: 115,
      semanaId: 9,
      analistaId: 2,
      saldoAnterior: 2,
      nuevoIngreso: 9,
      circulacion: 1,
      resuelto: 6,
      conLugar: 5,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 6,
      historicoCirculacion: 12,
    },
    {
      id: 116,
      semanaId: 8,
      analistaId: 4,
      saldoAnterior: 11,
      nuevoIngreso: 3,
      circulacion: 4,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 12,
      historicoCirculacion: 6,
    },
    {
      id: 117,
      semanaId: 9,
      analistaId: 4,
      saldoAnterior: 12,
      nuevoIngreso: 6,
      circulacion: 1,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 1,
      pendiente: 12,
      historicoCirculacion: 6,
    },
    {
      id: 118,
      semanaId: 9,
      analistaId: 8,
      saldoAnterior: 0,
      nuevoIngreso: 17,
      circulacion: 4,
      resuelto: 16,
      conLugar: 16,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 12,
    },
    {
      id: 119,
      semanaId: 9,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 14,
      circulacion: 2,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 6,
      historicoCirculacion: 12,
    },
    {
      id: 120,
      semanaId: 9,
      analistaId: 10,
      saldoAnterior: 1,
      nuevoIngreso: 17,
      circulacion: 3,
      resuelto: 12,
      conLugar: 12,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 7,
      historicoCirculacion: 17,
    },
    {
      id: 121,
      semanaId: 9,
      analistaId: 15,
      saldoAnterior: 2,
      nuevoIngreso: 2,
      circulacion: 1,
      resuelto: 3,
      conLugar: 3,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 5,
    },
    {
      id: 122,
      semanaId: 9,
      analistaId: 11,
      saldoAnterior: 11,
      nuevoIngreso: 4,
      circulacion: 1,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 9,
      historicoCirculacion: 2,
    },
    {
      id: 123,
      semanaId: 9,
      analistaId: 14,
      saldoAnterior: 6,
      nuevoIngreso: 5,
      circulacion: 2,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 7,
      historicoCirculacion: 5,
    },
    {
      id: 124,
      semanaId: 9,
      analistaId: 13,
      saldoAnterior: 12,
      nuevoIngreso: 2,
      circulacion: 4,
      resuelto: 10,
      conLugar: 10,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 7,
      historicoCirculacion: 6,
    },
    {
      id: 125,
      semanaId: 9,
      analistaId: 12,
      saldoAnterior: 8,
      nuevoIngreso: 6,
      circulacion: 3,
      resuelto: 7,
      conLugar: 6,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 10,
      historicoCirculacion: 6,
    },
    {
      id: 126,
      semanaId: 9,
      analistaId: 17,
      saldoAnterior: 5,
      nuevoIngreso: 10,
      circulacion: 0,
      resuelto: 6,
      conLugar: 5,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 2,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 4,
      historicoCirculacion: 0,
    },
    {
      id: 127,
      semanaId: 9,
      analistaId: 3,
      saldoAnterior: 5,
      nuevoIngreso: 11,
      circulacion: 1,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 2,
      pendiente: 9,
      historicoCirculacion: 7,
    },
    {
      id: 129,
      semanaId: 10,
      analistaId: 1,
      saldoAnterior: 4,
      nuevoIngreso: 14,
      circulacion: 2,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 11,
      historicoCirculacion: 8,
    },
    {
      id: 130,
      semanaId: 10,
      analistaId: 9,
      saldoAnterior: 4,
      nuevoIngreso: 14,
      circulacion: 2,
      resuelto: 15,
      conLugar: 15,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 2,
      historicoCirculacion: 11,
    },
    {
      id: 131,
      semanaId: 10,
      analistaId: 2,
      saldoAnterior: 6,
      nuevoIngreso: 15,
      circulacion: 0,
      resuelto: 7,
      conLugar: 5,
      sinLugar: 2,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 1,
      dictamenCirculacion: 1,
      requerido: 0,
      pendiente: 12,
      historicoCirculacion: 12,
    },
    {
      id: 132,
      semanaId: 10,
      analistaId: 8,
      saldoAnterior: 3,
      nuevoIngreso: 13,
      circulacion: 4,
      resuelto: 15,
      conLugar: 15,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 10,
    },
    {
      id: 133,
      semanaId: 10,
      analistaId: 3,
      saldoAnterior: 9,
      nuevoIngreso: 14,
      circulacion: 4,
      resuelto: 8,
      conLugar: 7,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 1,
      pendiente: 17,
      historicoCirculacion: 6,
    },
    {
      id: 134,
      semanaId: 10,
      analistaId: 12,
      saldoAnterior: 10,
      nuevoIngreso: 2,
      circulacion: 2,
      resuelto: 4,
      conLugar: 2,
      sinLugar: 0,
      parcial: 2,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 10,
      historicoCirculacion: 4,
    },
    {
      id: 135,
      semanaId: 10,
      analistaId: 13,
      saldoAnterior: 7,
      nuevoIngreso: 4,
      circulacion: 2,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 8,
      historicoCirculacion: 5,
    },
    {
      id: 136,
      semanaId: 10,
      analistaId: 14,
      saldoAnterior: 7,
      nuevoIngreso: 2,
      circulacion: 1,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 6,
      historicoCirculacion: 4,
    },
    {
      id: 137,
      semanaId: 10,
      analistaId: 11,
      saldoAnterior: 9,
      nuevoIngreso: 4,
      circulacion: 0,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 7,
      historicoCirculacion: 3,
    },
    {
      id: 138,
      semanaId: 10,
      analistaId: 15,
      saldoAnterior: 1,
      nuevoIngreso: 5,
      circulacion: 3,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 5,
      historicoCirculacion: 3,
    },
    {
      id: 139,
      semanaId: 10,
      analistaId: 6,
      saldoAnterior: 6,
      nuevoIngreso: 17,
      circulacion: 5,
      resuelto: 21,
      conLugar: 21,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 2,
      historicoCirculacion: 9,
    },
    {
      id: 140,
      semanaId: 10,
      analistaId: 10,
      saldoAnterior: 7,
      nuevoIngreso: 12,
      circulacion: 7,
      resuelto: 16,
      conLugar: 16,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 3,
      historicoCirculacion: 12,
    },
    {
      id: 142,
      semanaId: 10,
      analistaId: 17,
      saldoAnterior: 4,
      nuevoIngreso: 14,
      circulacion: 2,
      resuelto: 5,
      conLugar: 4,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 12,
      historicoCirculacion: 3,
    },
    {
      id: 143,
      semanaId: 10,
      analistaId: 4,
      saldoAnterior: 12,
      nuevoIngreso: 12,
      circulacion: 0,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 18,
      historicoCirculacion: 8,
    },
    {
      id: 144,
      semanaId: 11,
      analistaId: 9,
      saldoAnterior: 2,
      nuevoIngreso: 7,
      circulacion: 5,
      resuelto: 13,
      conLugar: 13,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 7,
    },
    {
      id: 145,
      semanaId: 11,
      analistaId: 13,
      saldoAnterior: 8,
      nuevoIngreso: 6,
      circulacion: 1,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 6,
      historicoCirculacion: 4,
    },
    {
      id: 146,
      semanaId: 11,
      analistaId: 15,
      saldoAnterior: 5,
      nuevoIngreso: 5,
      circulacion: 0,
      resuelto: 3,
      conLugar: 3,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 5,
      pendiente: 1,
      historicoCirculacion: 3,
    },
    {
      id: 147,
      semanaId: 11,
      analistaId: 11,
      saldoAnterior: 7,
      nuevoIngreso: 3,
      circulacion: 0,
      resuelto: 3,
      conLugar: 3,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 6,
      historicoCirculacion: 4,
    },
    {
      id: 148,
      semanaId: 11,
      analistaId: 14,
      saldoAnterior: 6,
      nuevoIngreso: 6,
      circulacion: 2,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 10,
      historicoCirculacion: 2,
    },
    {
      id: 149,
      semanaId: 11,
      analistaId: 12,
      saldoAnterior: 10,
      nuevoIngreso: 8,
      circulacion: 3,
      resuelto: 6,
      conLugar: 5,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 4,
      pendiente: 10,
      historicoCirculacion: 1,
    },
    {
      id: 150,
      semanaId: 11,
      analistaId: 8,
      saldoAnterior: 1,
      nuevoIngreso: 7,
      circulacion: 7,
      resuelto: 14,
      conLugar: 14,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 3,
    },
    {
      id: 151,
      semanaId: 11,
      analistaId: 2,
      saldoAnterior: 12,
      nuevoIngreso: 12,
      circulacion: 8,
      resuelto: 5,
      conLugar: 4,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 2,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 24,
      historicoCirculacion: 6,
    },
    {
      id: 152,
      semanaId: 11,
      analistaId: 17,
      saldoAnterior: 12,
      nuevoIngreso: 11,
      circulacion: 0,
      resuelto: 3,
      conLugar: 3,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 1,
      dictamenCirculacion: 3,
      requerido: 0,
      pendiente: 16,
      historicoCirculacion: 6,
    },
    {
      id: 153,
      semanaId: 11,
      analistaId: 4,
      saldoAnterior: 18,
      nuevoIngreso: 13,
      circulacion: 1,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 1,
      pendiente: 25,
      historicoCirculacion: 7,
    },
    {
      id: 154,
      semanaId: 11,
      analistaId: 3,
      saldoAnterior: 17,
      nuevoIngreso: 11,
      circulacion: 0,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 23,
      historicoCirculacion: 8,
    },
    {
      id: 155,
      semanaId: 11,
      analistaId: 1,
      saldoAnterior: 11,
      nuevoIngreso: 11,
      circulacion: 5,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 1,
      pendiente: 20,
      historicoCirculacion: 6,
    },
    {
      id: 156,
      semanaId: 11,
      analistaId: 6,
      saldoAnterior: 2,
      nuevoIngreso: 10,
      circulacion: 6,
      resuelto: 13,
      conLugar: 13,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 1,
      historicoCirculacion: 5,
    },
    {
      id: 158,
      semanaId: 11,
      analistaId: 10,
      saldoAnterior: 3,
      nuevoIngreso: 8,
      circulacion: 9,
      resuelto: 15,
      conLugar: 15,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 0,
      historicoCirculacion: 6,
    },
    {
      id: 159,
      semanaId: 9,
      analistaId: 7,
      saldoAnterior: 0,
      nuevoIngreso: 18,
      circulacion: 0,
      resuelto: 10,
      conLugar: 10,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 6,
      historicoCirculacion: 14,
    },
    {
      id: 160,
      semanaId: 12,
      analistaId: 9,
      saldoAnterior: 1,
      nuevoIngreso: 8,
      circulacion: 2,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 5,
    },
    {
      id: 161,
      semanaId: 10,
      analistaId: 7,
      saldoAnterior: 6,
      nuevoIngreso: 16,
      circulacion: 3,
      resuelto: 17,
      conLugar: 17,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 3,
      historicoCirculacion: 13,
    },
    {
      id: 162,
      semanaId: 12,
      analistaId: 3,
      saldoAnterior: 23,
      nuevoIngreso: 13,
      circulacion: 1,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 30,
      historicoCirculacion: 7,
    },
    {
      id: 163,
      semanaId: 12,
      analistaId: 4,
      saldoAnterior: 25,
      nuevoIngreso: 9,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 34,
      historicoCirculacion: 9,
    },
    {
      id: 164,
      semanaId: 12,
      analistaId: 11,
      saldoAnterior: 6,
      nuevoIngreso: 24,
      circulacion: 0,
      resuelto: 11,
      conLugar: 11,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 19,
      historicoCirculacion: 5,
    },
    {
      id: 165,
      semanaId: 12,
      analistaId: 14,
      saldoAnterior: 10,
      nuevoIngreso: 21,
      circulacion: 2,
      resuelto: 19,
      conLugar: 19,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 13,
      historicoCirculacion: 0,
    },
    {
      id: 166,
      semanaId: 11,
      analistaId: 7,
      saldoAnterior: 3,
      nuevoIngreso: 6,
      circulacion: 11,
      resuelto: 17,
      conLugar: 17,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 7,
    },
    {
      id: 167,
      semanaId: 12,
      analistaId: 13,
      saldoAnterior: 6,
      nuevoIngreso: 23,
      circulacion: 1,
      resuelto: 18,
      conLugar: 18,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 10,
      historicoCirculacion: 5,
    },
    {
      id: 168,
      semanaId: 12,
      analistaId: 15,
      saldoAnterior: 1,
      nuevoIngreso: 2,
      circulacion: 0,
      resuelto: 1,
      conLugar: 1,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 9,
    },
    {
      id: 169,
      semanaId: 12,
      analistaId: 12,
      saldoAnterior: 10,
      nuevoIngreso: 25,
      circulacion: 1,
      resuelto: 15,
      conLugar: 15,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 20,
      historicoCirculacion: 5,
    },
    {
      id: 170,
      semanaId: 12,
      analistaId: 1,
      saldoAnterior: 20,
      nuevoIngreso: 12,
      circulacion: 1,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 2,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 26,
      historicoCirculacion: 6,
    },
    {
      id: 171,
      semanaId: 12,
      analistaId: 2,
      saldoAnterior: 24,
      nuevoIngreso: 9,
      circulacion: 1,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 26,
      historicoCirculacion: 8,
    },
    {
      id: 172,
      semanaId: 12,
      analistaId: 17,
      saldoAnterior: 16,
      nuevoIngreso: 12,
      circulacion: 0,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 21,
      historicoCirculacion: 10,
    },
    {
      id: 173,
      semanaId: 12,
      analistaId: 7,
      saldoAnterior: 0,
      nuevoIngreso: 8,
      circulacion: 2,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 0,
      historicoCirculacion: 8,
    },
    {
      id: 174,
      semanaId: 12,
      analistaId: 6,
      saldoAnterior: 1,
      nuevoIngreso: 9,
      circulacion: 4,
      resuelto: 11,
      conLugar: 11,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 4,
    },
    {
      id: 175,
      semanaId: 12,
      analistaId: 10,
      saldoAnterior: 0,
      nuevoIngreso: 8,
      circulacion: 4,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 6,
    },
    {
      id: 176,
      semanaId: 12,
      analistaId: 8,
      saldoAnterior: 0,
      nuevoIngreso: 8,
      circulacion: 0,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 4,
    },
    {
      id: 177,
      semanaId: 13,
      analistaId: 9,
      saldoAnterior: 1,
      nuevoIngreso: 12,
      circulacion: 3,
      resuelto: 10,
      conLugar: 10,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 2,
      historicoCirculacion: 4,
    },
    {
      id: 178,
      semanaId: 13,
      analistaId: 17,
      saldoAnterior: 21,
      nuevoIngreso: 11,
      circulacion: 3,
      resuelto: 15,
      conLugar: 14,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 20,
      historicoCirculacion: 8,
    },
    {
      id: 179,
      semanaId: 13,
      analistaId: 2,
      saldoAnterior: 26,
      nuevoIngreso: 13,
      circulacion: 1,
      resuelto: 10,
      conLugar: 9,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 30,
      historicoCirculacion: 7,
    },
    {
      id: 180,
      semanaId: 13,
      analistaId: 14,
      saldoAnterior: 13,
      nuevoIngreso: 4,
      circulacion: 1,
      resuelto: 9,
      conLugar: 9,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 9,
      historicoCirculacion: 0,
    },
    {
      id: 181,
      semanaId: 13,
      analistaId: 8,
      saldoAnterior: 0,
      nuevoIngreso: 14,
      circulacion: 3,
      resuelto: 11,
      conLugar: 11,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 5,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 3,
    },
    {
      id: 182,
      semanaId: 13,
      analistaId: 7,
      saldoAnterior: 0,
      nuevoIngreso: 12,
      circulacion: 5,
      resuelto: 11,
      conLugar: 11,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 0,
      historicoCirculacion: 8,
    },
    {
      id: 183,
      semanaId: 13,
      analistaId: 13,
      saldoAnterior: 10,
      nuevoIngreso: 7,
      circulacion: 1,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 9,
      historicoCirculacion: 6,
    },
    {
      id: 184,
      semanaId: 13,
      analistaId: 15,
      saldoAnterior: 1,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 10,
    },
    {
      id: 185,
      semanaId: 13,
      analistaId: 11,
      saldoAnterior: 19,
      nuevoIngreso: 7,
      circulacion: 1,
      resuelto: 16,
      conLugar: 16,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 11,
      historicoCirculacion: 4,
    },
    {
      id: 186,
      semanaId: 13,
      analistaId: 12,
      saldoAnterior: 20,
      nuevoIngreso: 7,
      circulacion: 2,
      resuelto: 19,
      conLugar: 19,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 9,
      historicoCirculacion: 4,
    },
    {
      id: 187,
      semanaId: 13,
      analistaId: 10,
      saldoAnterior: 0,
      nuevoIngreso: 14,
      circulacion: 5,
      resuelto: 10,
      conLugar: 10,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 5,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 4,
      pendiente: 0,
      historicoCirculacion: 5,
    },
    {
      id: 188,
      semanaId: 13,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 16,
      circulacion: 3,
      resuelto: 12,
      conLugar: 12,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 6,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 4,
    },
    {
      id: 189,
      semanaId: 13,
      analistaId: 1,
      saldoAnterior: 26,
      nuevoIngreso: 12,
      circulacion: 1,
      resuelto: 7,
      conLugar: 6,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 29,
      historicoCirculacion: 7,
    },
    {
      id: 190,
      semanaId: 13,
      analistaId: 3,
      saldoAnterior: 30,
      nuevoIngreso: 13,
      circulacion: 5,
      resuelto: 18,
      conLugar: 15,
      sinLugar: 1,
      parcial: 2,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 29,
      historicoCirculacion: 2,
    },
    {
      id: 191,
      semanaId: 14,
      analistaId: 3,
      saldoAnterior: 29,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 29,
      historicoCirculacion: 3,
    },
    {
      id: 192,
      semanaId: 14,
      analistaId: 9,
      saldoAnterior: 2,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 8,
    },
    {
      id: 193,
      semanaId: 14,
      analistaId: 14,
      saldoAnterior: 9,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 9,
      historicoCirculacion: 0,
    },
    {
      id: 194,
      semanaId: 13,
      analistaId: 4,
      saldoAnterior: 34,
      nuevoIngreso: 10,
      circulacion: 1,
      resuelto: 9,
      conLugar: 9,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 35,
      historicoCirculacion: 8,
    },
    {
      id: 195,
      semanaId: 14,
      analistaId: 4,
      saldoAnterior: 35,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 35,
      historicoCirculacion: 9,
    },
    {
      id: 196,
      semanaId: 14,
      analistaId: 15,
      saldoAnterior: 1,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 10,
    },
    {
      id: 197,
      semanaId: 14,
      analistaId: 13,
      saldoAnterior: 9,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 9,
      historicoCirculacion: 8,
    },
    {
      id: 198,
      semanaId: 14,
      analistaId: 2,
      saldoAnterior: 30,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 30,
      historicoCirculacion: 7,
    },
    {
      id: 199,
      semanaId: 14,
      analistaId: 11,
      saldoAnterior: 11,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 11,
      historicoCirculacion: 4,
    },
    {
      id: 200,
      semanaId: 14,
      analistaId: 12,
      saldoAnterior: 9,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 9,
      historicoCirculacion: 5,
    },
    {
      id: 201,
      semanaId: 14,
      analistaId: 10,
      saldoAnterior: 0,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 14,
    },
    {
      id: 202,
      semanaId: 14,
      analistaId: 8,
      saldoAnterior: 0,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 9,
    },
    {
      id: 203,
      semanaId: 14,
      analistaId: 7,
      saldoAnterior: 0,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 14,
    },
    {
      id: 204,
      semanaId: 14,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 11,
    },
    {
      id: 205,
      semanaId: 14,
      analistaId: 17,
      saldoAnterior: 20,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 20,
      historicoCirculacion: 8,
    },
    {
      id: 206,
      semanaId: 14,
      analistaId: 1,
      saldoAnterior: 29,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 29,
      historicoCirculacion: 11,
    },
    {
      id: 207,
      semanaId: 15,
      analistaId: 1,
      saldoAnterior: 29,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 29,
      historicoCirculacion: 11,
    },
    {
      id: 208,
      semanaId: 15,
      analistaId: 15,
      saldoAnterior: 1,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 10,
    },
    {
      id: 209,
      semanaId: 16,
      analistaId: 1,
      saldoAnterior: 29,
      nuevoIngreso: 11,
      circulacion: 2,
      resuelto: 11,
      conLugar: 11,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 1,
      dictamenCirculacion: 1,
      requerido: 0,
      pendiente: 29,
      historicoCirculacion: 9,
    },
    {
      id: 210,
      semanaId: 15,
      analistaId: 17,
      saldoAnterior: 20,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 20,
      historicoCirculacion: 8,
    },
    {
      id: 211,
      semanaId: 16,
      analistaId: 17,
      saldoAnterior: 20,
      nuevoIngreso: 12,
      circulacion: 3,
      resuelto: 12,
      conLugar: 11,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 23,
      historicoCirculacion: 5,
    },
    {
      id: 212,
      semanaId: 15,
      analistaId: 14,
      saldoAnterior: 9,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 9,
      historicoCirculacion: 0,
    },
    {
      id: 213,
      semanaId: 16,
      analistaId: 14,
      saldoAnterior: 9,
      nuevoIngreso: 6,
      circulacion: 0,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 10,
      historicoCirculacion: 0,
    },
    {
      id: 214,
      semanaId: 15,
      analistaId: 4,
      saldoAnterior: 35,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 35,
      historicoCirculacion: 9,
    },
    {
      id: 215,
      semanaId: 16,
      analistaId: 4,
      saldoAnterior: 35,
      nuevoIngreso: 12,
      circulacion: 3,
      resuelto: 9,
      conLugar: 9,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 0,
      pendiente: 40,
      historicoCirculacion: 6,
    },
    {
      id: 216,
      semanaId: 15,
      analistaId: 8,
      saldoAnterior: 0,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 9,
    },
    {
      id: 217,
      semanaId: 16,
      analistaId: 8,
      saldoAnterior: 0,
      nuevoIngreso: 17,
      circulacion: 4,
      resuelto: 14,
      conLugar: 14,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 4,
      historicoCirculacion: 5,
    },
    {
      id: 218,
      semanaId: 15,
      analistaId: 3,
      saldoAnterior: 29,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 29,
      historicoCirculacion: 3,
    },
    {
      id: 219,
      semanaId: 16,
      analistaId: 3,
      saldoAnterior: 29,
      nuevoIngreso: 12,
      circulacion: 0,
      resuelto: 11,
      conLugar: 11,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 2,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 28,
      historicoCirculacion: 3,
    },
    {
      id: 220,
      semanaId: 17,
      analistaId: 14,
      saldoAnterior: 10,
      nuevoIngreso: 3,
      circulacion: 1,
      resuelto: 10,
      conLugar: 10,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 4,
      historicoCirculacion: 0,
    },
    {
      id: 221,
      semanaId: 15,
      analistaId: 7,
      saldoAnterior: 0,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 14,
    },
    {
      id: 222,
      semanaId: 15,
      analistaId: 9,
      saldoAnterior: 2,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 8,
    },
    {
      id: 223,
      semanaId: 16,
      analistaId: 7,
      saldoAnterior: 0,
      nuevoIngreso: 19,
      circulacion: 8,
      resuelto: 18,
      conLugar: 18,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 6,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 6,
    },
    {
      id: 224,
      semanaId: 16,
      analistaId: 9,
      saldoAnterior: 2,
      nuevoIngreso: 16,
      circulacion: 5,
      resuelto: 14,
      conLugar: 14,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 6,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 3,
    },
    {
      id: 225,
      semanaId: 15,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 11,
    },
    {
      id: 226,
      semanaId: 16,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 24,
      circulacion: 5,
      resuelto: 23,
      conLugar: 23,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 5,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 6,
    },
    {
      id: 227,
      semanaId: 15,
      analistaId: 2,
      saldoAnterior: 30,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 30,
      historicoCirculacion: 7,
    },
    {
      id: 228,
      semanaId: 16,
      analistaId: 2,
      saldoAnterior: 30,
      nuevoIngreso: 12,
      circulacion: 1,
      resuelto: 15,
      conLugar: 15,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 1,
      dictamenCirculacion: 1,
      requerido: 0,
      pendiente: 26,
      historicoCirculacion: 6,
    },
    {
      id: 229,
      semanaId: 15,
      analistaId: 10,
      saldoAnterior: 0,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 14,
    },
    {
      id: 230,
      semanaId: 16,
      analistaId: 10,
      saldoAnterior: 0,
      nuevoIngreso: 18,
      circulacion: 5,
      resuelto: 17,
      conLugar: 17,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 1,
      historicoCirculacion: 9,
    },
    {
      id: 231,
      semanaId: 15,
      analistaId: 12,
      saldoAnterior: 9,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 9,
      historicoCirculacion: 5,
    },
    {
      id: 232,
      semanaId: 16,
      analistaId: 12,
      saldoAnterior: 9,
      nuevoIngreso: 4,
      circulacion: 1,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 8,
      historicoCirculacion: 4,
    },
    {
      id: 233,
      semanaId: 15,
      analistaId: 13,
      saldoAnterior: 9,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 9,
      historicoCirculacion: 8,
    },
    {
      id: 234,
      semanaId: 16,
      analistaId: 13,
      saldoAnterior: 9,
      nuevoIngreso: 3,
      circulacion: 1,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 10,
      historicoCirculacion: 7,
    },
    {
      id: 235,
      semanaId: 16,
      analistaId: 15,
      saldoAnterior: 1,
      nuevoIngreso: 7,
      circulacion: 1,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 1,
      historicoCirculacion: 9,
    },
    {
      id: 236,
      semanaId: 15,
      analistaId: 11,
      saldoAnterior: 11,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 11,
      historicoCirculacion: 4,
    },
    {
      id: 237,
      semanaId: 16,
      analistaId: 11,
      saldoAnterior: 11,
      nuevoIngreso: 4,
      circulacion: 0,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 9,
      historicoCirculacion: 4,
    },
    {
      id: 238,
      semanaId: 17,
      analistaId: 9,
      saldoAnterior: 3,
      nuevoIngreso: 13,
      circulacion: 0,
      resuelto: 9,
      conLugar: 9,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 7,
      historicoCirculacion: 9,
    },
    {
      id: 239,
      semanaId: 17,
      analistaId: 15,
      saldoAnterior: 1,
      nuevoIngreso: 4,
      circulacion: 3,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 2,
      historicoCirculacion: 8,
    },
    {
      id: 240,
      semanaId: 17,
      analistaId: 13,
      saldoAnterior: 10,
      nuevoIngreso: 9,
      circulacion: 0,
      resuelto: 13,
      conLugar: 13,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 4,
      pendiente: 2,
      historicoCirculacion: 8,
    },
    {
      id: 241,
      semanaId: 18,
      analistaId: 14,
      saldoAnterior: 4,
      nuevoIngreso: 5,
      circulacion: 0,
      resuelto: 3,
      conLugar: 3,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 5,
      historicoCirculacion: 0,
    },
    {
      id: 242,
      semanaId: 17,
      analistaId: 12,
      saldoAnterior: 8,
      nuevoIngreso: 8,
      circulacion: 3,
      resuelto: 12,
      conLugar: 12,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 5,
      historicoCirculacion: 3,
    },
    {
      id: 243,
      semanaId: 17,
      analistaId: 11,
      saldoAnterior: 9,
      nuevoIngreso: 8,
      circulacion: 0,
      resuelto: 12,
      conLugar: 12,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 4,
      historicoCirculacion: 4,
    },
    {
      id: 244,
      semanaId: 17,
      analistaId: 4,
      saldoAnterior: 40,
      nuevoIngreso: 17,
      circulacion: 0,
      resuelto: 26,
      conLugar: 26,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 31,
      historicoCirculacion: 8,
    },
    {
      id: 245,
      semanaId: 17,
      analistaId: 7,
      saldoAnterior: 3,
      nuevoIngreso: 12,
      circulacion: 2,
      resuelto: 13,
      conLugar: 13,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 2,
      historicoCirculacion: 10,
    },
    {
      id: 246,
      semanaId: 17,
      analistaId: 10,
      saldoAnterior: 1,
      nuevoIngreso: 12,
      circulacion: 4,
      resuelto: 10,
      conLugar: 10,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 6,
      pendiente: 1,
      historicoCirculacion: 10,
    },
    {
      id: 247,
      semanaId: 17,
      analistaId: 1,
      saldoAnterior: 29,
      nuevoIngreso: 20,
      circulacion: 3,
      resuelto: 27,
      conLugar: 27,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 24,
      historicoCirculacion: 10,
    },
    {
      id: 248,
      semanaId: 17,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 15,
      circulacion: 2,
      resuelto: 13,
      conLugar: 13,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 0,
      historicoCirculacion: 10,
    },
    {
      id: 249,
      semanaId: 17,
      analistaId: 8,
      saldoAnterior: 4,
      nuevoIngreso: 13,
      circulacion: 2,
      resuelto: 17,
      conLugar: 17,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 6,
    },
    {
      id: 250,
      semanaId: 17,
      analistaId: 3,
      saldoAnterior: 28,
      nuevoIngreso: 21,
      circulacion: 1,
      resuelto: 30,
      conLugar: 27,
      sinLugar: 2,
      parcial: 0,
      caducado: 1,
      dictamen: 4,
      dictamenCustodia: 4,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 16,
      historicoCirculacion: 6,
    },
    {
      id: 251,
      semanaId: 17,
      analistaId: 2,
      saldoAnterior: 26,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 26,
      historicoCirculacion: 10,
    },
    {
      id: 252,
      semanaId: 17,
      analistaId: 18,
      saldoAnterior: 0,
      nuevoIngreso: 17,
      circulacion: 0,
      resuelto: 13,
      conLugar: 13,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 4,
      historicoCirculacion: 0,
    },
    {
      id: 253,
      semanaId: 18,
      analistaId: 9,
      saldoAnterior: 7,
      nuevoIngreso: 6,
      circulacion: 1,
      resuelto: 10,
      conLugar: 10,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 8,
    },
    {
      id: 254,
      semanaId: 18,
      analistaId: 11,
      saldoAnterior: 4,
      nuevoIngreso: 5,
      circulacion: 0,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 5,
      historicoCirculacion: 5,
    },
    {
      id: 255,
      semanaId: 18,
      analistaId: 13,
      saldoAnterior: 2,
      nuevoIngreso: 6,
      circulacion: 2,
      resuelto: 6,
      conLugar: 5,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 4,
      historicoCirculacion: 10,
    },
    {
      id: 256,
      semanaId: 18,
      analistaId: 12,
      saldoAnterior: 5,
      nuevoIngreso: 6,
      circulacion: 1,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 6,
      historicoCirculacion: 4,
    },
    {
      id: 257,
      semanaId: 18,
      analistaId: 7,
      saldoAnterior: 2,
      nuevoIngreso: 5,
      circulacion: 4,
      resuelto: 10,
      conLugar: 10,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 8,
    },
    {
      id: 258,
      semanaId: 18,
      analistaId: 15,
      saldoAnterior: 2,
      nuevoIngreso: 4,
      circulacion: 1,
      resuelto: 1,
      conLugar: 1,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 6,
      historicoCirculacion: 8,
    },
    {
      id: 259,
      semanaId: 18,
      analistaId: 4,
      saldoAnterior: 31,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 31,
      historicoCirculacion: 8,
    },
    {
      id: 260,
      semanaId: 18,
      analistaId: 8,
      saldoAnterior: 1,
      nuevoIngreso: 7,
      circulacion: 6,
      resuelto: 13,
      conLugar: 13,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 1,
    },
    {
      id: 261,
      semanaId: 18,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 7,
      circulacion: 7,
      resuelto: 12,
      conLugar: 12,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 7,
    },
    {
      id: 262,
      semanaId: 18,
      analistaId: 10,
      saldoAnterior: 1,
      nuevoIngreso: 5,
      circulacion: 13,
      resuelto: 9,
      conLugar: 9,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 7,
      pendiente: 2,
      historicoCirculacion: 3,
    },
    {
      id: 263,
      semanaId: 18,
      analistaId: 3,
      saldoAnterior: 16,
      nuevoIngreso: 12,
      circulacion: 0,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 19,
      historicoCirculacion: 14,
    },
    {
      id: 264,
      semanaId: 18,
      analistaId: 1,
      saldoAnterior: 24,
      nuevoIngreso: 13,
      circulacion: 0,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 32,
      historicoCirculacion: 12,
    },
    {
      id: 265,
      semanaId: 18,
      analistaId: 18,
      saldoAnterior: 4,
      nuevoIngreso: 16,
      circulacion: 0,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 11,
      historicoCirculacion: 0,
    },
    {
      id: 266,
      semanaId: 19,
      analistaId: 9,
      saldoAnterior: 3,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 9,
    },
    {
      id: 267,
      semanaId: 18,
      analistaId: 2,
      saldoAnterior: 26,
      nuevoIngreso: 17,
      circulacion: 1,
      resuelto: 30,
      conLugar: 30,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 2,
      dictamenCirculacion: 1,
      requerido: 0,
      pendiente: 11,
      historicoCirculacion: 9,
    },
    {
      id: 268,
      semanaId: 19,
      analistaId: 2,
      saldoAnterior: 11,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 11,
      historicoCirculacion: 15,
    },
  ];

  try {
    await db.insert(PamCabeceraSemanal).values(cabeceras);
    console.log(
      `✅ Se insertaron ${cabeceras.length} cabeceras semanales exitosamente`,
    );
  } catch (error) {
    console.error("❌ Error al insertar cabeceras semanales:", error);
    throw error;
  }
}
