import { InferInsertModel } from "drizzle-orm";
import { db } from "@/lib/drizzle";
import { PamCabeceraSemanal } from "@/db/schema/PAM_CABECERA_SEMANAL";

export type NuevaCabeceraSemanal = InferInsertModel<typeof PamCabeceraSemanal>;

export async function seedPamCabeceraSemanal() {
  // Asumiendo que tenemos 12 semanas (ids 1-12)
  const cabeceras: NuevaCabeceraSemanal[] = [
    {
      id: 2,
      semanaId: 6,
      analistaId: 5,
      saldoAnterior: 2,
      nuevoIngreso: 6,
      circulacion: 1,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 2,
      historicoCirculacion: 1,
    },
    {
      id: 3,
      semanaId: 5,
      analistaId: 5,
      saldoAnterior: 0,
      nuevoIngreso: 8,
      circulacion: 0,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 2,
      historicoCirculacion: 0,
    },
    {
      id: 4,
      semanaId: 2,
      analistaId: 1,
      saldoAnterior: 0,
      nuevoIngreso: 25,
      circulacion: 0,
      resuelto: 11,
      conLugar: 11,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 6,
      pendiente: 8,
      historicoCirculacion: 0,
    },
    {
      id: 5,
      semanaId: 2,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 17,
      circulacion: 0,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 8,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 0,
    },
    {
      id: 6,
      semanaId: 6,
      analistaId: 8,
      saldoAnterior: 7,
      nuevoIngreso: 15,
      circulacion: 4,
      resuelto: 18,
      conLugar: 18,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 7,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 3,
    },
    {
      id: 7,
      semanaId: 2,
      analistaId: 8,
      saldoAnterior: 0,
      nuevoIngreso: 14,
      circulacion: 0,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 0,
      historicoCirculacion: 0,
    },
    {
      id: 8,
      semanaId: 6,
      analistaId: 2,
      saldoAnterior: 5,
      nuevoIngreso: 7,
      circulacion: 2,
      resuelto: 12,
      conLugar: 9,
      sinLugar: 0,
      parcial: 2,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 9,
    },
    {
      id: 10,
      semanaId: 3,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 2,
      circulacion: 0,
      resuelto: 1,
      conLugar: 1,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 9,
    },
    {
      id: 11,
      semanaId: 3,
      analistaId: 8,
      saldoAnterior: 0,
      nuevoIngreso: 6,
      circulacion: 1,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 6,
    },
    {
      id: 12,
      semanaId: 2,
      analistaId: 2,
      saldoAnterior: 0,
      nuevoIngreso: 15,
      circulacion: 0,
      resuelto: 7,
      conLugar: 6,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 1,
      dictamenCirculacion: 1,
      requerido: 6,
      pendiente: 0,
      historicoCirculacion: 0,
    },
    {
      id: 14,
      semanaId: 3,
      analistaId: 2,
      saldoAnterior: 0,
      nuevoIngreso: 7,
      circulacion: 1,
      resuelto: 6,
      conLugar: 5,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 7,
    },
    {
      id: 15,
      semanaId: 4,
      analistaId: 8,
      saldoAnterior: 1,
      nuevoIngreso: 11,
      circulacion: 2,
      resuelto: 11,
      conLugar: 11,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 4,
    },
    {
      id: 16,
      semanaId: 5,
      analistaId: 8,
      saldoAnterior: 2,
      nuevoIngreso: 9,
      circulacion: 0,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 7,
      historicoCirculacion: 5,
    },
    {
      id: 17,
      semanaId: 4,
      analistaId: 2,
      saldoAnterior: 0,
      nuevoIngreso: 8,
      circulacion: 4,
      resuelto: 6,
      conLugar: 4,
      sinLugar: 0,
      parcial: 1,
      caducado: 1,
      dictamen: 3,
      dictamenCustodia: 3,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 1,
      historicoCirculacion: 5,
    },
    {
      id: 18,
      semanaId: 3,
      analistaId: 1,
      saldoAnterior: 7,
      nuevoIngreso: 9,
      circulacion: 3,
      resuelto: 11,
      conLugar: 11,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 5,
      historicoCirculacion: 3,
    },
    {
      id: 19,
      semanaId: 7,
      analistaId: 5,
      saldoAnterior: 3,
      nuevoIngreso: 7,
      circulacion: 1,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 3,
      historicoCirculacion: 2,
    },
    {
      id: 20,
      semanaId: 4,
      analistaId: 1,
      saldoAnterior: 5,
      nuevoIngreso: 5,
      circulacion: 5,
      resuelto: 9,
      conLugar: 8,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 1,
      dictamenCirculacion: 1,
      requerido: 2,
      pendiente: 2,
      historicoCirculacion: 1,
    },
    {
      id: 21,
      semanaId: 5,
      analistaId: 1,
      saldoAnterior: 2,
      nuevoIngreso: 8,
      circulacion: 1,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 1,
      dictamenCirculacion: 2,
      requerido: 1,
      pendiente: 7,
      historicoCirculacion: 4,
    },
    {
      id: 22,
      semanaId: 6,
      analistaId: 1,
      saldoAnterior: 7,
      nuevoIngreso: 5,
      circulacion: 2,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 4,
      historicoCirculacion: 6,
    },
    {
      id: 23,
      semanaId: 7,
      analistaId: 1,
      saldoAnterior: 4,
      nuevoIngreso: 7,
      circulacion: 2,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 6,
      historicoCirculacion: 8,
    },
    {
      id: 24,
      semanaId: 2,
      analistaId: 3,
      saldoAnterior: 0,
      nuevoIngreso: 28,
      circulacion: 0,
      resuelto: 14,
      conLugar: 10,
      sinLugar: 1,
      parcial: 2,
      caducado: 1,
      dictamen: 2,
      dictamenCustodia: 1,
      dictamenCirculacion: 1,
      requerido: 5,
      pendiente: 7,
      historicoCirculacion: 0,
    },
    {
      id: 26,
      semanaId: 7,
      analistaId: 8,
      saldoAnterior: 1,
      nuevoIngreso: 14,
      circulacion: 0,
      resuelto: 11,
      conLugar: 11,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 10,
    },
    {
      id: 27,
      semanaId: 2,
      analistaId: 7,
      saldoAnterior: 0,
      nuevoIngreso: 13,
      circulacion: 0,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 0,
    },
    {
      id: 28,
      semanaId: 2,
      analistaId: 10,
      saldoAnterior: 0,
      nuevoIngreso: 12,
      circulacion: 0,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 0,
      historicoCirculacion: 0,
    },
    {
      id: 29,
      semanaId: 3,
      analistaId: 10,
      saldoAnterior: 0,
      nuevoIngreso: 6,
      circulacion: 0,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 6,
    },
    {
      id: 31,
      semanaId: 3,
      analistaId: 7,
      saldoAnterior: 0,
      nuevoIngreso: 5,
      circulacion: 1,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 4,
    },
    {
      id: 32,
      semanaId: 4,
      analistaId: 7,
      saldoAnterior: 0,
      nuevoIngreso: 12,
      circulacion: 0,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 5,
    },
    {
      id: 33,
      semanaId: 5,
      analistaId: 2,
      saldoAnterior: 1,
      nuevoIngreso: 7,
      circulacion: 0,
      resuelto: 2,
      conLugar: 1,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 5,
      historicoCirculacion: 10,
    },
    {
      id: 34,
      semanaId: 2,
      analistaId: 9,
      saldoAnterior: 0,
      nuevoIngreso: 13,
      circulacion: 0,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 5,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 0,
      historicoCirculacion: 0,
    },
    {
      id: 35,
      semanaId: 3,
      analistaId: 9,
      saldoAnterior: 0,
      nuevoIngreso: 5,
      circulacion: 2,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 0,
      historicoCirculacion: 5,
    },
    {
      id: 36,
      semanaId: 5,
      analistaId: 7,
      saldoAnterior: 1,
      nuevoIngreso: 9,
      circulacion: 4,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 11,
      historicoCirculacion: 4,
    },
    {
      id: 37,
      semanaId: 4,
      analistaId: 9,
      saldoAnterior: 0,
      nuevoIngreso: 10,
      circulacion: 1,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 5,
    },
    {
      id: 38,
      semanaId: 7,
      analistaId: 2,
      saldoAnterior: 3,
      nuevoIngreso: 5,
      circulacion: 1,
      resuelto: 5,
      conLugar: 4,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 2,
      pendiente: 1,
      historicoCirculacion: 8,
    },
    {
      id: 39,
      semanaId: 5,
      analistaId: 9,
      saldoAnterior: 2,
      nuevoIngreso: 9,
      circulacion: 4,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 11,
      historicoCirculacion: 3,
    },
    {
      id: 40,
      semanaId: 6,
      analistaId: 9,
      saldoAnterior: 11,
      nuevoIngreso: 15,
      circulacion: 0,
      resuelto: 19,
      conLugar: 19,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 2,
      historicoCirculacion: 7,
    },
    {
      id: 41,
      semanaId: 6,
      analistaId: 7,
      saldoAnterior: 11,
      nuevoIngreso: 15,
      circulacion: 1,
      resuelto: 20,
      conLugar: 20,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 6,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 6,
    },
    {
      id: 42,
      semanaId: 7,
      analistaId: 9,
      saldoAnterior: 2,
      nuevoIngreso: 14,
      circulacion: 3,
      resuelto: 11,
      conLugar: 9,
      sinLugar: 2,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 6,
      historicoCirculacion: 9,
    },
    {
      id: 43,
      semanaId: 3,
      analistaId: 3,
      saldoAnterior: 7,
      nuevoIngreso: 9,
      circulacion: 4,
      resuelto: 11,
      conLugar: 9,
      sinLugar: 1,
      parcial: 0,
      caducado: 1,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 5,
      pendiente: 3,
      historicoCirculacion: 3,
    },
    {
      id: 44,
      semanaId: 4,
      analistaId: 3,
      saldoAnterior: 3,
      nuevoIngreso: 5,
      circulacion: 4,
      resuelto: 7,
      conLugar: 3,
      sinLugar: 2,
      parcial: 1,
      caducado: 1,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 3,
      historicoCirculacion: 5,
    },
    {
      id: 45,
      semanaId: 5,
      analistaId: 3,
      saldoAnterior: 3,
      nuevoIngreso: 8,
      circulacion: 0,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 5,
      historicoCirculacion: 7,
    },
    {
      id: 46,
      semanaId: 6,
      analistaId: 3,
      saldoAnterior: 5,
      nuevoIngreso: 4,
      circulacion: 2,
      resuelto: 4,
      conLugar: 3,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 6,
      historicoCirculacion: 6,
    },
    {
      id: 47,
      semanaId: 8,
      analistaId: 2,
      saldoAnterior: 1,
      nuevoIngreso: 8,
      circulacion: 1,
      resuelto: 6,
      conLugar: 5,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 2,
      historicoCirculacion: 11,
    },
    {
      id: 48,
      semanaId: 4,
      analistaId: 10,
      saldoAnterior: 1,
      nuevoIngreso: 9,
      circulacion: 0,
      resuelto: 10,
      conLugar: 10,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 6,
    },
    {
      id: 49,
      semanaId: 5,
      analistaId: 10,
      saldoAnterior: 0,
      nuevoIngreso: 10,
      circulacion: 1,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 7,
      historicoCirculacion: 5,
    },
    {
      id: 50,
      semanaId: 4,
      analistaId: 6,
      saldoAnterior: 1,
      nuevoIngreso: 11,
      circulacion: 2,
      resuelto: 12,
      conLugar: 12,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 7,
    },
    {
      id: 51,
      semanaId: 5,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 7,
      circulacion: 0,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 9,
    },
    {
      id: 52,
      semanaId: 6,
      analistaId: 10,
      saldoAnterior: 7,
      nuevoIngreso: 15,
      circulacion: 0,
      resuelto: 16,
      conLugar: 16,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 1,
      historicoCirculacion: 7,
    },
    {
      id: 53,
      semanaId: 6,
      analistaId: 6,
      saldoAnterior: 3,
      nuevoIngreso: 14,
      circulacion: 7,
      resuelto: 18,
      conLugar: 18,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 6,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 4,
    },
    {
      id: 54,
      semanaId: 7,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 17,
      circulacion: 1,
      resuelto: 13,
      conLugar: 13,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 2,
      historicoCirculacion: 9,
    },
    {
      id: 55,
      semanaId: 7,
      analistaId: 10,
      saldoAnterior: 1,
      nuevoIngreso: 14,
      circulacion: 0,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 7,
      historicoCirculacion: 12,
    },
    {
      id: 56,
      semanaId: 7,
      analistaId: 3,
      saldoAnterior: 6,
      nuevoIngreso: 4,
      circulacion: 2,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 3,
      pendiente: 6,
      historicoCirculacion: 5,
    },
    {
      id: 57,
      semanaId: 2,
      analistaId: 12,
      saldoAnterior: 0,
      nuevoIngreso: 11,
      circulacion: 0,
      resuelto: 6,
      conLugar: 5,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 2,
      historicoCirculacion: 0,
    },
    {
      id: 58,
      semanaId: 3,
      analistaId: 12,
      saldoAnterior: 2,
      nuevoIngreso: 11,
      circulacion: 0,
      resuelto: 7,
      conLugar: 6,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 2,
      historicoCirculacion: 3,
    },
    {
      id: 59,
      semanaId: 4,
      analistaId: 12,
      saldoAnterior: 2,
      nuevoIngreso: 11,
      circulacion: 1,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 5,
      historicoCirculacion: 6,
    },
    {
      id: 60,
      semanaId: 5,
      analistaId: 12,
      saldoAnterior: 5,
      nuevoIngreso: 4,
      circulacion: 4,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 8,
      historicoCirculacion: 4,
    },
    {
      id: 61,
      semanaId: 8,
      analistaId: 9,
      saldoAnterior: 6,
      nuevoIngreso: 8,
      circulacion: 1,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 5,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 2,
      historicoCirculacion: 10,
    },
    {
      id: 62,
      semanaId: 2,
      analistaId: 11,
      saldoAnterior: 0,
      nuevoIngreso: 8,
      circulacion: 0,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 0,
    },
    {
      id: 63,
      semanaId: 3,
      analistaId: 11,
      saldoAnterior: 3,
      nuevoIngreso: 10,
      circulacion: 0,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 7,
      historicoCirculacion: 0,
    },
    {
      id: 64,
      semanaId: 4,
      analistaId: 11,
      saldoAnterior: 7,
      nuevoIngreso: 15,
      circulacion: 0,
      resuelto: 9,
      conLugar: 9,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 11,
      historicoCirculacion: 2,
    },
    {
      id: 65,
      semanaId: 5,
      analistaId: 11,
      saldoAnterior: 11,
      nuevoIngreso: 5,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 15,
      historicoCirculacion: 4,
    },
    {
      id: 66,
      semanaId: 6,
      analistaId: 11,
      saldoAnterior: 15,
      nuevoIngreso: 2,
      circulacion: 0,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 13,
      historicoCirculacion: 5,
    },
    {
      id: 67,
      semanaId: 7,
      analistaId: 11,
      saldoAnterior: 13,
      nuevoIngreso: 3,
      circulacion: 1,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 10,
      historicoCirculacion: 4,
    },
    {
      id: 68,
      semanaId: 8,
      analistaId: 11,
      saldoAnterior: 10,
      nuevoIngreso: 7,
      circulacion: 1,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 11,
      historicoCirculacion: 3,
    },
    {
      id: 73,
      semanaId: 2,
      analistaId: 13,
      saldoAnterior: 0,
      nuevoIngreso: 12,
      circulacion: 0,
      resuelto: 3,
      conLugar: 2,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 4,
      historicoCirculacion: 0,
    },
    {
      id: 74,
      semanaId: 3,
      analistaId: 13,
      saldoAnterior: 4,
      nuevoIngreso: 6,
      circulacion: 2,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 5,
      historicoCirculacion: 3,
    },
    {
      id: 75,
      semanaId: 4,
      analistaId: 13,
      saldoAnterior: 5,
      nuevoIngreso: 11,
      circulacion: 2,
      resuelto: 7,
      conLugar: 6,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 9,
      historicoCirculacion: 4,
    },
    {
      id: 77,
      semanaId: 5,
      analistaId: 13,
      saldoAnterior: 9,
      nuevoIngreso: 5,
      circulacion: 0,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 9,
      historicoCirculacion: 6,
    },
    {
      id: 78,
      semanaId: 2,
      analistaId: 14,
      saldoAnterior: 0,
      nuevoIngreso: 9,
      circulacion: 0,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 4,
      historicoCirculacion: 0,
    },
    {
      id: 79,
      semanaId: 6,
      analistaId: 13,
      saldoAnterior: 9,
      nuevoIngreso: 4,
      circulacion: 0,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 11,
      historicoCirculacion: 7,
    },
    {
      id: 80,
      semanaId: 3,
      analistaId: 14,
      saldoAnterior: 4,
      nuevoIngreso: 5,
      circulacion: 2,
      resuelto: 6,
      conLugar: 5,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 4,
      historicoCirculacion: 1,
    },
    {
      id: 81,
      semanaId: 4,
      analistaId: 14,
      saldoAnterior: 4,
      nuevoIngreso: 6,
      circulacion: 0,
      resuelto: 4,
      conLugar: 4,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 3,
      historicoCirculacion: 2,
    },
    {
      id: 82,
      semanaId: 7,
      analistaId: 7,
      saldoAnterior: 1,
      nuevoIngreso: 9,
      circulacion: 1,
      resuelto: 10,
      conLugar: 9,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 11,
    },
    {
      id: 83,
      semanaId: 5,
      analistaId: 14,
      saldoAnterior: 3,
      nuevoIngreso: 7,
      circulacion: 2,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 8,
      historicoCirculacion: 3,
    },
    {
      id: 84,
      semanaId: 7,
      analistaId: 13,
      saldoAnterior: 11,
      nuevoIngreso: 7,
      circulacion: 1,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 4,
      pendiente: 7,
      historicoCirculacion: 6,
    },
    {
      id: 85,
      semanaId: 6,
      analistaId: 14,
      saldoAnterior: 8,
      nuevoIngreso: 4,
      circulacion: 1,
      resuelto: 3,
      conLugar: 3,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 7,
      historicoCirculacion: 4,
    },
    {
      id: 86,
      semanaId: 7,
      analistaId: 14,
      saldoAnterior: 7,
      nuevoIngreso: 2,
      circulacion: 4,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 7,
      historicoCirculacion: 3,
    },
    {
      id: 87,
      semanaId: 6,
      analistaId: 12,
      saldoAnterior: 8,
      nuevoIngreso: 3,
      circulacion: 1,
      resuelto: 5,
      conLugar: 4,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 6,
      historicoCirculacion: 6,
    },
    {
      id: 88,
      semanaId: 7,
      analistaId: 12,
      saldoAnterior: 6,
      nuevoIngreso: 5,
      circulacion: 3,
      resuelto: 3,
      conLugar: 2,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 4,
      pendiente: 6,
      historicoCirculacion: 4,
    },
    {
      id: 89,
      semanaId: 2,
      analistaId: 15,
      saldoAnterior: 0,
      nuevoIngreso: 4,
      circulacion: 0,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 0,
    },
    {
      id: 90,
      semanaId: 3,
      analistaId: 15,
      saldoAnterior: 1,
      nuevoIngreso: 3,
      circulacion: 0,
      resuelto: 1,
      conLugar: 1,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 1,
    },
    {
      id: 91,
      semanaId: 4,
      analistaId: 15,
      saldoAnterior: 3,
      nuevoIngreso: 4,
      circulacion: 0,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 2,
      historicoCirculacion: 1,
    },
    {
      id: 92,
      semanaId: 5,
      analistaId: 15,
      saldoAnterior: 2,
      nuevoIngreso: 2,
      circulacion: 0,
      resuelto: 3,
      conLugar: 3,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 4,
    },
    {
      id: 93,
      semanaId: 6,
      analistaId: 15,
      saldoAnterior: 1,
      nuevoIngreso: 5,
      circulacion: 0,
      resuelto: 2,
      conLugar: 2,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 2,
      historicoCirculacion: 4,
    },
    {
      id: 94,
      semanaId: 2,
      analistaId: 4,
      saldoAnterior: 0,
      nuevoIngreso: 29,
      circulacion: 0,
      resuelto: 9,
      conLugar: 7,
      sinLugar: 0,
      parcial: 2,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 2,
      pendiente: 17,
      historicoCirculacion: 0,
    },
    {
      id: 95,
      semanaId: 3,
      analistaId: 4,
      saldoAnterior: 17,
      nuevoIngreso: 8,
      circulacion: 0,
      resuelto: 8,
      conLugar: 8,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 17,
      historicoCirculacion: 3,
    },
    {
      id: 96,
      semanaId: 8,
      analistaId: 7,
      saldoAnterior: 0,
      nuevoIngreso: 10,
      circulacion: 0,
      resuelto: 7,
      conLugar: 6,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 11,
    },
    {
      id: 97,
      semanaId: 4,
      analistaId: 4,
      saldoAnterior: 17,
      nuevoIngreso: 4,
      circulacion: 1,
      resuelto: 7,
      conLugar: 2,
      sinLugar: 4,
      parcial: 1,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 3,
      pendiente: 11,
      historicoCirculacion: 2,
    },
    {
      id: 98,
      semanaId: 5,
      analistaId: 4,
      saldoAnterior: 11,
      nuevoIngreso: 7,
      circulacion: 0,
      resuelto: 6,
      conLugar: 5,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 10,
      historicoCirculacion: 6,
    },
    {
      id: 99,
      semanaId: 6,
      analistaId: 4,
      saldoAnterior: 10,
      nuevoIngreso: 3,
      circulacion: 0,
      resuelto: 3,
      conLugar: 3,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 1,
      pendiente: 9,
      historicoCirculacion: 8,
    },
    {
      id: 100,
      semanaId: 7,
      analistaId: 4,
      saldoAnterior: 9,
      nuevoIngreso: 9,
      circulacion: 3,
      resuelto: 6,
      conLugar: 4,
      sinLugar: 0,
      parcial: 2,
      caducado: 0,
      dictamen: 3,
      dictamenCustodia: 1,
      dictamenCirculacion: 2,
      requerido: 1,
      pendiente: 11,
      historicoCirculacion: 6,
    },
    {
      id: 101,
      semanaId: 8,
      analistaId: 5,
      saldoAnterior: 3,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 3,
      historicoCirculacion: 4,
    },
    {
      id: 102,
      semanaId: 8,
      analistaId: 1,
      saldoAnterior: 6,
      nuevoIngreso: 5,
      circulacion: 2,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 1,
      requerido: 3,
      pendiente: 4,
      historicoCirculacion: 8,
    },
    {
      id: 103,
      semanaId: 8,
      analistaId: 10,
      saldoAnterior: 7,
      nuevoIngreso: 10,
      circulacion: 1,
      resuelto: 9,
      conLugar: 8,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 8,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 12,
    },
    {
      id: 104,
      semanaId: 8,
      analistaId: 6,
      saldoAnterior: 2,
      nuevoIngreso: 9,
      circulacion: 2,
      resuelto: 9,
      conLugar: 9,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 10,
    },
    {
      id: 105,
      semanaId: 8,
      analistaId: 8,
      saldoAnterior: 2,
      nuevoIngreso: 8,
      circulacion: 0,
      resuelto: 6,
      conLugar: 6,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 4,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 12,
    },
    {
      id: 106,
      semanaId: 8,
      analistaId: 3,
      saldoAnterior: 6,
      nuevoIngreso: 7,
      circulacion: 4,
      resuelto: 9,
      conLugar: 8,
      sinLugar: 0,
      parcial: 1,
      caducado: 0,
      dictamen: 2,
      dictamenCustodia: 1,
      dictamenCirculacion: 1,
      requerido: 1,
      pendiente: 5,
      historicoCirculacion: 5,
    },
    {
      id: 107,
      semanaId: 8,
      analistaId: 14,
      saldoAnterior: 7,
      nuevoIngreso: 6,
      circulacion: 0,
      resuelto: 3,
      conLugar: 3,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 4,
      pendiente: 6,
      historicoCirculacion: 3,
    },
    {
      id: 108,
      semanaId: 7,
      analistaId: 15,
      saldoAnterior: 2,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 6,
    },
    {
      id: 109,
      semanaId: 8,
      analistaId: 12,
      saldoAnterior: 6,
      nuevoIngreso: 7,
      circulacion: 2,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 2,
      pendiente: 8,
      historicoCirculacion: 7,
    },
    {
      id: 110,
      semanaId: 8,
      analistaId: 15,
      saldoAnterior: 2,
      nuevoIngreso: 1,
      circulacion: 0,
      resuelto: 1,
      conLugar: 1,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 6,
    },
    {
      id: 111,
      semanaId: 8,
      analistaId: 13,
      saldoAnterior: 7,
      nuevoIngreso: 12,
      circulacion: 3,
      resuelto: 7,
      conLugar: 7,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 3,
      pendiente: 12,
      historicoCirculacion: 7,
    },
    {
      id: 112,
      semanaId: 9,
      analistaId: 9,
      saldoAnterior: 2,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 16,
    },
    {
      id: 113,
      semanaId: 8,
      analistaId: 17,
      saldoAnterior: 0,
      nuevoIngreso: 8,
      circulacion: 0,
      resuelto: 3,
      conLugar: 2,
      sinLugar: 1,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 5,
      historicoCirculacion: 0,
    },
    {
      id: 114,
      semanaId: 9,
      analistaId: 1,
      saldoAnterior: 4,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 4,
      historicoCirculacion: 12,
    },
    {
      id: 115,
      semanaId: 9,
      analistaId: 2,
      saldoAnterior: 2,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 13,
    },
    {
      id: 116,
      semanaId: 8,
      analistaId: 4,
      saldoAnterior: 11,
      nuevoIngreso: 3,
      circulacion: 4,
      resuelto: 5,
      conLugar: 5,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 1,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 12,
      historicoCirculacion: 6,
    },
    {
      id: 117,
      semanaId: 9,
      analistaId: 4,
      saldoAnterior: 12,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 12,
      historicoCirculacion: 7,
    },
    {
      id: 118,
      semanaId: 9,
      analistaId: 8,
      saldoAnterior: 0,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 16,
    },
    {
      id: 119,
      semanaId: 9,
      analistaId: 6,
      saldoAnterior: 0,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 0,
      historicoCirculacion: 14,
    },
    {
      id: 120,
      semanaId: 9,
      analistaId: 10,
      saldoAnterior: 1,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 1,
      historicoCirculacion: 20,
    },
    {
      id: 121,
      semanaId: 9,
      analistaId: 15,
      saldoAnterior: 2,
      nuevoIngreso: 1,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 1,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 2,
      historicoCirculacion: 6,
    },
    {
      id: 122,
      semanaId: 9,
      analistaId: 11,
      saldoAnterior: 11,
      nuevoIngreso: 1,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 12,
      historicoCirculacion: 3,
    },
    {
      id: 123,
      semanaId: 9,
      analistaId: 14,
      saldoAnterior: 6,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 6,
      historicoCirculacion: 7,
    },
    {
      id: 124,
      semanaId: 9,
      analistaId: 13,
      saldoAnterior: 12,
      nuevoIngreso: 1,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 13,
      historicoCirculacion: 10,
    },
    {
      id: 125,
      semanaId: 9,
      analistaId: 12,
      saldoAnterior: 8,
      nuevoIngreso: 0,
      circulacion: 0,
      resuelto: 0,
      conLugar: 0,
      sinLugar: 0,
      parcial: 0,
      caducado: 0,
      dictamen: 0,
      dictamenCustodia: 0,
      dictamenCirculacion: 0,
      requerido: 0,
      pendiente: 8,
      historicoCirculacion: 9,
    },
  ];

  try {
    await db.insert(PamCabeceraSemanal).values(cabeceras);
    console.log(
      `✅ Se insertaron ${cabeceras.length} cabeceras semanales exitosamente`,
    );
  } catch (error) {
    console.error("❌ Error al insertar cabeceras semanales:", error);
    throw error;
  }
}
